package com.health.entity;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.ACCOUNT
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Object account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.NAME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Object name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.PASSWORD
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Object password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.STATE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Short state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.AMOUNT
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.LOCATIONID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer locationid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.ACCOUNT
     *
     * @return the value of ACCOUNT.ACCOUNT
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Object getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.ACCOUNT
     *
     * @param account the value for ACCOUNT.ACCOUNT
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setAccount(Object account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.NAME
     *
     * @return the value of ACCOUNT.NAME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Object getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.NAME
     *
     * @param name the value for ACCOUNT.NAME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setName(Object name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.PASSWORD
     *
     * @return the value of ACCOUNT.PASSWORD
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Object getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.PASSWORD
     *
     * @param password the value for ACCOUNT.PASSWORD
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setPassword(Object password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.STATE
     *
     * @return the value of ACCOUNT.STATE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.STATE
     *
     * @param state the value for ACCOUNT.STATE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.AMOUNT
     *
     * @return the value of ACCOUNT.AMOUNT
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.AMOUNT
     *
     * @param amount the value for ACCOUNT.AMOUNT
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.LOCATIONID
     *
     * @return the value of ACCOUNT.LOCATIONID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getLocationid() {
        return locationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.LOCATIONID
     *
     * @param locationid the value for ACCOUNT.LOCATIONID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setLocationid(Integer locationid) {
        this.locationid = locationid;
    }
}