package com.health.entity;

public class Cashflow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CASHFLOW.CASHFLOWID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer cashflowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CASHFLOW.ACCOUNTID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Object accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CASHFLOW.REFERAMOUNT
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Long referamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CASHFLOW.TIME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Object time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CASHFLOW.OPERATION
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Short operation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CASHFLOW.CASHFLOWID
     *
     * @return the value of CASHFLOW.CASHFLOWID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getCashflowid() {
        return cashflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CASHFLOW.CASHFLOWID
     *
     * @param cashflowid the value for CASHFLOW.CASHFLOWID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setCashflowid(Integer cashflowid) {
        this.cashflowid = cashflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CASHFLOW.ACCOUNTID
     *
     * @return the value of CASHFLOW.ACCOUNTID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Object getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CASHFLOW.ACCOUNTID
     *
     * @param accountid the value for CASHFLOW.ACCOUNTID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setAccountid(Object accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CASHFLOW.REFERAMOUNT
     *
     * @return the value of CASHFLOW.REFERAMOUNT
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Long getReferamount() {
        return referamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CASHFLOW.REFERAMOUNT
     *
     * @param referamount the value for CASHFLOW.REFERAMOUNT
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setReferamount(Long referamount) {
        this.referamount = referamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CASHFLOW.TIME
     *
     * @return the value of CASHFLOW.TIME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Object getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CASHFLOW.TIME
     *
     * @param time the value for CASHFLOW.TIME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setTime(Object time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CASHFLOW.OPERATION
     *
     * @return the value of CASHFLOW.OPERATION
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Short getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CASHFLOW.OPERATION
     *
     * @param operation the value for CASHFLOW.OPERATION
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setOperation(Short operation) {
        this.operation = operation;
    }
}