package com.health.entity;

public class Chargepack {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGEPACK.CHARGEPACKID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer chargepackid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGEPACK.CHARGEID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer chargeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGEPACK.PACKAGEID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer packageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGEPACK.NUMBER
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGEPACK.CHARGEPACKID
     *
     * @return the value of CHARGEPACK.CHARGEPACKID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getChargepackid() {
        return chargepackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGEPACK.CHARGEPACKID
     *
     * @param chargepackid the value for CHARGEPACK.CHARGEPACKID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setChargepackid(Integer chargepackid) {
        this.chargepackid = chargepackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGEPACK.CHARGEID
     *
     * @return the value of CHARGEPACK.CHARGEID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getChargeid() {
        return chargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGEPACK.CHARGEID
     *
     * @param chargeid the value for CHARGEPACK.CHARGEID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setChargeid(Integer chargeid) {
        this.chargeid = chargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGEPACK.PACKAGEID
     *
     * @return the value of CHARGEPACK.PACKAGEID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getPackageid() {
        return packageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGEPACK.PACKAGEID
     *
     * @param packageid the value for CHARGEPACK.PACKAGEID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setPackageid(Integer packageid) {
        this.packageid = packageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGEPACK.NUMBER
     *
     * @return the value of CHARGEPACK.NUMBER
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGEPACK.NUMBER
     *
     * @param number the value for CHARGEPACK.NUMBER
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}