package com.health.entity;

public class Charge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.CHARGEID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer chargeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.ACCOUNT
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Object account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.AMOUNT
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.PRETIME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Object pretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.TIME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Object time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.STATE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Short state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.CHARGEID
     *
     * @return the value of CHARGE.CHARGEID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getChargeid() {
        return chargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.CHARGEID
     *
     * @param chargeid the value for CHARGE.CHARGEID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setChargeid(Integer chargeid) {
        this.chargeid = chargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.ACCOUNT
     *
     * @return the value of CHARGE.ACCOUNT
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Object getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.ACCOUNT
     *
     * @param account the value for CHARGE.ACCOUNT
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setAccount(Object account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.AMOUNT
     *
     * @return the value of CHARGE.AMOUNT
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.AMOUNT
     *
     * @param amount the value for CHARGE.AMOUNT
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.PRETIME
     *
     * @return the value of CHARGE.PRETIME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Object getPretime() {
        return pretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.PRETIME
     *
     * @param pretime the value for CHARGE.PRETIME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setPretime(Object pretime) {
        this.pretime = pretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.TIME
     *
     * @return the value of CHARGE.TIME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Object getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.TIME
     *
     * @param time the value for CHARGE.TIME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setTime(Object time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.STATE
     *
     * @return the value of CHARGE.STATE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.STATE
     *
     * @param state the value for CHARGE.STATE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setState(Short state) {
        this.state = state;
    }
}