package com.health.entity;

public class Guideitem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUIDEITEM.GUIDEITEMID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer guideitemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUIDEITEM.GUIDEID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer guideid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUIDEITEM.ITEMID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUIDEITEM.SUMMARY
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Object summary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUIDEITEM.GUIDEITEMID
     *
     * @return the value of GUIDEITEM.GUIDEITEMID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getGuideitemid() {
        return guideitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUIDEITEM.GUIDEITEMID
     *
     * @param guideitemid the value for GUIDEITEM.GUIDEITEMID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setGuideitemid(Integer guideitemid) {
        this.guideitemid = guideitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUIDEITEM.GUIDEID
     *
     * @return the value of GUIDEITEM.GUIDEID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getGuideid() {
        return guideid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUIDEITEM.GUIDEID
     *
     * @param guideid the value for GUIDEITEM.GUIDEID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setGuideid(Integer guideid) {
        this.guideid = guideid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUIDEITEM.ITEMID
     *
     * @return the value of GUIDEITEM.ITEMID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUIDEITEM.ITEMID
     *
     * @param itemid the value for GUIDEITEM.ITEMID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUIDEITEM.SUMMARY
     *
     * @return the value of GUIDEITEM.SUMMARY
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Object getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUIDEITEM.SUMMARY
     *
     * @param summary the value for GUIDEITEM.SUMMARY
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setSummary(Object summary) {
        this.summary = summary;
    }
}