package com.health.entity;

public class Guide {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUIDE.GUIDEID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer guideid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUIDE.STATE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Short state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUIDE.TIME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Object time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUIDE.PERSONINFOID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer personinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUIDE.ALLSUMMARY
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Object allsummary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUIDE.GUIDEID
     *
     * @return the value of GUIDE.GUIDEID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getGuideid() {
        return guideid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUIDE.GUIDEID
     *
     * @param guideid the value for GUIDE.GUIDEID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setGuideid(Integer guideid) {
        this.guideid = guideid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUIDE.STATE
     *
     * @return the value of GUIDE.STATE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUIDE.STATE
     *
     * @param state the value for GUIDE.STATE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUIDE.TIME
     *
     * @return the value of GUIDE.TIME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Object getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUIDE.TIME
     *
     * @param time the value for GUIDE.TIME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setTime(Object time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUIDE.PERSONINFOID
     *
     * @return the value of GUIDE.PERSONINFOID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getPersoninfoid() {
        return personinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUIDE.PERSONINFOID
     *
     * @param personinfoid the value for GUIDE.PERSONINFOID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setPersoninfoid(Integer personinfoid) {
        this.personinfoid = personinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUIDE.ALLSUMMARY
     *
     * @return the value of GUIDE.ALLSUMMARY
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Object getAllsummary() {
        return allsummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUIDE.ALLSUMMARY
     *
     * @param allsummary the value for GUIDE.ALLSUMMARY
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setAllsummary(Object allsummary) {
        this.allsummary = allsummary;
    }
}