package com.health.entity;

public class Location {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCATION.LOCATIONID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer locationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCATION.PARENTID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCATION.LOCATIONNAME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Object locationname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOCATION.LOCATIONID
     *
     * @return the value of LOCATION.LOCATIONID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getLocationid() {
        return locationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOCATION.LOCATIONID
     *
     * @param locationid the value for LOCATION.LOCATIONID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setLocationid(Integer locationid) {
        this.locationid = locationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOCATION.PARENTID
     *
     * @return the value of LOCATION.PARENTID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOCATION.PARENTID
     *
     * @param parentid the value for LOCATION.PARENTID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOCATION.LOCATIONNAME
     *
     * @return the value of LOCATION.LOCATIONNAME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Object getLocationname() {
        return locationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOCATION.LOCATIONNAME
     *
     * @param locationname the value for LOCATION.LOCATIONNAME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setLocationname(Object locationname) {
        this.locationname = locationname;
    }
}