package com.health.entity;

public class Parameter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARAMETER.PARAMETERID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer parameterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARAMETER.PARENTID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARAMETER.PARAMNAME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    private Object paramname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARAMETER.PARAMETERID
     *
     * @return the value of PARAMETER.PARAMETERID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getParameterid() {
        return parameterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARAMETER.PARAMETERID
     *
     * @param parameterid the value for PARAMETER.PARAMETERID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setParameterid(Integer parameterid) {
        this.parameterid = parameterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARAMETER.PARENTID
     *
     * @return the value of PARAMETER.PARENTID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARAMETER.PARENTID
     *
     * @param parentid the value for PARAMETER.PARENTID
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARAMETER.PARAMNAME
     *
     * @return the value of PARAMETER.PARAMNAME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public Object getParamname() {
        return paramname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARAMETER.PARAMNAME
     *
     * @param paramname the value for PARAMETER.PARAMNAME
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    public void setParamname(Object paramname) {
        this.paramname = paramname;
    }
}