<script src="<%=request.getContextPath() %>/js/jquery-2.1.4.min.js"></script>
<script src="<%=request.getContextPath() %>/js/bootstrap.min.js"></script>
<script src="<%=request.getContextPath() %>/js/jquery-ui.custom.min.js"></script>
<script src="<%=request.getContextPath() %>/js/jquery.ui.touch-punch.min.js"></script>
<script src="<%=request.getContextPath() %>/js/moment.min.js"></script>
<script src="<%=request.getContextPath() %>/js/fullcalendar.min.js"></script>
<script src="<%=request.getContextPath() %>/js/bootbox.js"></script>
<script src="<%=request.getContextPath() %>/js/jquery.easypiechart.min.js"></script>
<script src="<%=request.getContextPath() %>/js/jquery.sparkline.index.min.js"></script>
<script src="<%=request.getContextPath() %>/js/jquery.flot.min.js"></script>
<script src="<%=request.getContextPath() %>/js/jquery.flot.pie.min.js"></script>
<script src="<%=request.getContextPath() %>/js/jquery.flot.resize.min.js"></script>
<script src="<%=request.getContextPath() %>/js/ace-elements.min.js"></script>
<script src="<%=request.getContextPath() %>/js/ace.min.js"></script>
<script src="<%=request.getContextPath() %>/js/vue.js"></script>
<script src="<%=request.getContextPath() %>/js/json2.js"></script>
<script src="<%=request.getContextPath() %>/js/jquery.validate.min.js"></script>
<script src="<%=request.getContextPath() %>/js/messages_zh.js"></script>
<script src="<%=request.getContextPath() %>/js/vue-fullcalendar.min.js"></script>
<script src="<%=request.getContextPath() %>/js/move_port.js"></script>
