package com.health.mapper;

import com.health.entity.Cashflow;
import com.health.entity.CashflowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CashflowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASHFLOW
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int countByExample(CashflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASHFLOW
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int deleteByExample(CashflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASHFLOW
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int deleteByPrimaryKey(Integer cashflowid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASHFLOW
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int insert(Cashflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASHFLOW
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int insertSelective(Cashflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASHFLOW
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    List<Cashflow> selectByExample(CashflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASHFLOW
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    Cashflow selectByPrimaryKey(Integer cashflowid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASHFLOW
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") Cashflow record, @Param("example") CashflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASHFLOW
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByExample(@Param("record") Cashflow record, @Param("example") CashflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASHFLOW
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByPrimaryKeySelective(Cashflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASHFLOW
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByPrimaryKey(Cashflow record);
}