package com.health.mapper;

import com.health.entity.Charge;
import com.health.entity.ChargeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int countByExample(ChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int deleteByExample(ChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int deleteByPrimaryKey(Integer chargeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int insert(Charge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int insertSelective(Charge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    List<Charge> selectByExample(ChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    Charge selectByPrimaryKey(Integer chargeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") Charge record, @Param("example") ChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByExample(@Param("record") Charge record, @Param("example") ChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByPrimaryKeySelective(Charge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByPrimaryKey(Charge record);
}