package com.health.mapper;

import com.health.entity.Chargepack;
import com.health.entity.ChargepackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChargepackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGEPACK
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int countByExample(ChargepackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGEPACK
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int deleteByExample(ChargepackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGEPACK
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int deleteByPrimaryKey(Integer chargepackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGEPACK
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int insert(Chargepack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGEPACK
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int insertSelective(Chargepack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGEPACK
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    List<Chargepack> selectByExample(ChargepackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGEPACK
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    Chargepack selectByPrimaryKey(Integer chargepackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGEPACK
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") Chargepack record, @Param("example") ChargepackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGEPACK
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByExample(@Param("record") Chargepack record, @Param("example") ChargepackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGEPACK
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByPrimaryKeySelective(Chargepack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGEPACK
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByPrimaryKey(Chargepack record);
}