package com.health.mapper;

import com.health.entity.Guide;
import com.health.entity.GuideExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GuideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int countByExample(GuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int deleteByExample(GuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int deleteByPrimaryKey(Integer guideid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int insert(Guide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int insertSelective(Guide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    List<Guide> selectByExample(GuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    Guide selectByPrimaryKey(Integer guideid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") Guide record, @Param("example") GuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByExample(@Param("record") Guide record, @Param("example") GuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByPrimaryKeySelective(Guide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDE
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByPrimaryKey(Guide record);
}