package com.health.mapper;

import com.health.entity.Guideitem;
import com.health.entity.GuideitemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GuideitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDEITEM
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int countByExample(GuideitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDEITEM
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int deleteByExample(GuideitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDEITEM
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int deleteByPrimaryKey(Integer guideitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDEITEM
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int insert(Guideitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDEITEM
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int insertSelective(Guideitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDEITEM
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    List<Guideitem> selectByExample(GuideitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDEITEM
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    Guideitem selectByPrimaryKey(Integer guideitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDEITEM
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") Guideitem record, @Param("example") GuideitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDEITEM
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByExample(@Param("record") Guideitem record, @Param("example") GuideitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDEITEM
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByPrimaryKeySelective(Guideitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUIDEITEM
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByPrimaryKey(Guideitem record);
}