package com.health.mapper;

import com.health.entity.Location;
import com.health.entity.LocationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int countByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int deleteByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int deleteByPrimaryKey(Integer locationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int insert(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int insertSelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    List<Location> selectByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    Location selectByPrimaryKey(Integer locationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") Location record, @Param("example") LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByExample(@Param("record") Location record, @Param("example") LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByPrimaryKeySelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION
     *
     * @mbggenerated Mon Jun 18 13:09:43 CST 2018
     */
    int updateByPrimaryKey(Location record);
}